name: Windows Build (Stable)

on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: windows-latest

    env:
      ICONV_URL: https://codeload.github.com/win-iconv/win-iconv/zip
      ICONV_VER: 0.0.8

    steps:
    - name: Download stable release
      shell: bash
      run: |
        curl -LO https://www.freetds.org/files/stable/freetds-${{ env.FREETDS_VERSION }}.tar.gz
        tar -xzf freetds-${{ env.FREETDS_VERSION }}.tar.gz
        mv freetds-${{ env.FREETDS_VERSION }} freetds
        cd freetds

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install dependencies
      shell: powershell
      run: |
        choco install -y openssl --version=3.1.1
        choco install -y gperf
        choco install -y 7zip

    - name: Build Iconv
      shell: cmd
      run: |
        curl -sSf %ICONV_URL%/v%ICONV_VER% -o win_iconv.zip
        7z x win_iconv.zip
        ren win-iconv-%ICONV_VER% iconv
        mkdir iconv-build
        cd iconv-build
        cmake -G "NMake Makefiles" ^
              -DBUILD_STATIC=on ^
              -DBUILD_SHARED=off ^
              -DCMAKE_BUILD_TYPE=Release ^
              ../iconv
        nmake
        cd ..

    - name: Prepare iconv
      shell: powershell
      run: |
        New-Item -ItemType Directory -Force -Path "${{ github.workspace }}/iconv-install"
        Copy-Item -Path "iconv/iconv.h" -Destination "${{ github.workspace }}/iconv-install/"
        Copy-Item -Path "iconv-build/iconv.lib" -Destination "${{ github.workspace }}/iconv-install/"

    - name: Build FreeTDS
      shell: cmd
      run: |
        cd freetds
        configure.bat ^
          --prefix=${{ github.workspace }}\freetds_install ^
          --enable-msdblib ^
          --enable-sybase-compat ^
          --with-tdsver=7.4 ^
          --with-openssl=no ^
          --with-libiconv-prefix=${{ github.workspace }}\iconv-install ^
          --disable-threadsafe

        nmake
        nmake install

    - name: Verify build
      shell: cmd
      run: |
        ${{ github.workspace }}\freetds_install\bin\tsql -C

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: freetds-windows
        path: ${{ github.workspace }}\freetds_install
