name: Windows Native Build

on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: windows-latest

    env:
      FREETDS_VERSION: 1.4.12
      ICONV_URL: https://codeload.github.com/win-iconv/win-iconv/zip
      ICONV_VER: 0.0.8

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install dependencies
      shell: powershell
      run: |
        choco install -y openssl --version=3.1.1
        choco install -y gperf
        choco install -y 7zip
        choco install -y perl # 需要 perl 来运行 configure 脚本

    - name: Download and extract
      shell: cmd
      run: |
        curl -LO https://www.freetds.org/files/stable/freetds-%FREETDS_VERSION%.tar.gz
        7z x freetds-%FREETDS_VERSION%.tar.gz
        7z x freetds-%FREETDS_VERSION%.tar
        ren freetds-%FREETDS_VERSION% freetds

    - name: Build Iconv
      shell: cmd
      run: |
        curl -sSf %ICONV_URL%/v%ICONV_VER% -o win_iconv.zip
        7z x win_iconv.zip
        ren win-iconv-%ICONV_VER% iconv
        mkdir iconv-build
        cd iconv-build
        cmake -G "NMake Makefiles" ^
              -DBUILD_STATIC=on ^
              -DBUILD_SHARED=off ^
              -DCMAKE_BUILD_TYPE=Release ^
              ../iconv
        nmake
        cd ..

    - name: Configure FreeTDS
      shell: cmd
      working-directory: ./freetds
      run: |
        mkdir %CD%\..\iconv-install
        copy ..\iconv\iconv.h %CD%\..\iconv-install\
        copy ..\iconv-build\iconv.lib %CD%\..\iconv-install\
        
        perl configure ^
          --prefix=%CD%\..\freetds_install ^
          --enable-msdblib ^
          --enable-sybase-compat ^
          --with-tdsver=7.4 ^
          --with-openssl=no ^
          --with-libiconv-prefix=%CD%\..\iconv-install ^
          --disable-threadsafe

    - name: Build FreeTDS
      shell: cmd
      working-directory: ./freetds
      run: |
        nmake /f Makefile
        nmake /f Makefile install

    - name: Verify build
      shell: cmd
      run: |
        %CD%\freetds_install\bin\tsql -C

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: freetds-windows
        path: freetds_install
