name: Windows Build (Autotools)

on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: windows-latest

    env:
      ICONV_URL: https://codeload.github.com/win-iconv/win-iconv/zip
      ICONV_VER: 0.0.8

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install dependencies
      shell: cmd
      run: |
        choco install -y openssl --version=3.1.1
        choco install -y gperf
        choco install -y 7zip
        choco install -y make
        choco install -y msys2 --params="/NoUpdate"
        echo C:\msys64\usr\bin >> "%GITHUB_PATH%"

    - name: Build Iconv
      shell: cmd
      run: |
        curl -sSf %ICONV_URL%/v%ICONV_VER% -o win_iconv.zip
        7z x win_iconv.zip
        ren win-iconv-%ICONV_VER% iconv
        mkdir iconv-build
        cd iconv-build
        cmake -G "NMake Makefiles" ^
              -DBUILD_STATIC=on ^
              -DBUILD_SHARED=off ^
              -DCMAKE_BUILD_TYPE=Release ^
              ../iconv
        nmake
        cd ..

    - name: Verify MSVC tools
      shell: cmd
      run: |
        where cl
        where nmake
        where cmake

    - name: Prepare build environment
      shell: bash
      run: |
        mkdir -p ${{ github.workspace }}/iconv-install
        cp iconv/iconv.h ${{ github.workspace }}/iconv-install/
        cp iconv-build/iconv.lib ${{ github.workspace }}/iconv-install/
        ls -la ${{ github.workspace }}/iconv-install/

    - name: Configure and Build FreeTDS
      shell: bash
      run: |
        # 设置 MSYS2 环境
        export PATH="/c/msys64/usr/bin:$PATH"
        
        # 生成 configure 脚本
        autoreconf -fvi

        # 配置和构建
        ./configure \
          --prefix=${{ github.workspace }}/freetds_install \
          --enable-msdblib \
          --enable-sybase-compat \
          --with-tdsver=auto \
          --with-openssl=no \
          --with-libiconv-prefix=${{ github.workspace }}/iconv-install \
          --disable-threadsafe

        make -j$(nproc)
        make install

        # 验证构建
        ${{ github.workspace }}/freetds_install/bin/tsql -C

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-freetds-build
        path: |
          ${{ github.workspace }}/freetds_install/**/*
