name: Windows-NoIconv

on:
    push:
        branches: [ '**' ]
        paths-ignore:
            - '.github/workflows/macos.yml'
            - '.github/workflows/linux.yml'
    pull_request:
        branches: [ '**' ]
        paths-ignore:
            - '.github/workflows/macos.yml'
            - '.github/workflows/linux.yml'
    workflow_dispatch:

permissions: read-all

jobs:
    build:
        runs-on: windows-latest

        env:
            PREFIX: /freetds
            ICONV_URL: https://codeload.github.com/win-iconv/win-iconv/zip
            ICONV_VER: 0.0.8

        steps:
        - uses: actions/checkout@v4

        - uses: ilammy/msvc-dev-cmd@v1

        - name: Install dependencies
          run: |
            choco install openssl --version=3.1.1 -y
            choco install gperf -y
            choco install 7zip.install -y
            echo "C:\Program Files\7-Zip" >> $env:GITHUB_PATH

        - name: Build iconv
          shell: bash
          run: |
            curl -sSf ${ICONV_URL}/v${ICONV_VER} -o win_iconv.zip
            7z x win_iconv.zip
            mv win-iconv-${ICONV_VER} iconv
            mkdir iconv-build
            cd iconv-build
            cmake -G "NMake Makefiles" \
                  -DBUILD_STATIC=on \
                  -DBUILD_SHARED=off \
                  -DBUILD_EXECUTABLE=off \
                  -DBUILD_TEST=on \
                  -DCMAKE_BUILD_TYPE=Release \
                  ../iconv
            nmake
            cd ..

        - name: Build FreeTDS
          shell: bash
          run: |
            mkdir -p build
            cd build
            cmake -G "NMake Makefiles" \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DENABLE_MSDBLIB=on \
                  -DWITH_OPENSSL=ON \
                  -DWITH_ICONV=off \
                  -DDISABLE_ICONV=ON
                  -DICONV_INCLUDE_DIR=../iconv \
                  -DICONV_LIBRARY=../iconv-build/iconv.lib \
                  -DCMAKE_INSTALL_PREFIX="$PREFIX" \
                  ..
            nmake
            nmake install

        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: windows-build
            path: |
              ${{ env.PREFIX }}/**/*
              ./build/**/*
