name: Windows

on:
    push:
        branches:
            - '**'
        paths-ignore:
            - .github/workflows/macos.yml
            - .github/workflows/linux.yml
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
            - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
    pull_request:
        branches:
            - '**'
        paths-ignore:
            - .github/workflows/macos.yml
            - .github/workflows/linux.yml

    workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:

    build:

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest]

        env:
            PREFIX: /freetds
            ICONV_URL: https://codeload.github.com/win-iconv/win-iconv/zip
            ICONV_VER: 0.0.8

        steps:

        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            fetch-depth: 0

        - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0

        #- name: Install OpenSSL & perf
        #  run: |
        #    choco install openssl --version=3.1.1
        #    choco install gperf

        - name: Install & build dependencies
          shell:  bash
          run: |
            mkdir -p build/lib
            cd build
            cmake -G "NMake Makefiles" \
                    -DCMAKE_BUILD_TYPE=Release \
                    -DENABLE_MSDBLIB=on \
                    -DWITH_OPENSSL=off \
                    -DWITH_ICONV=off \       # 如果需要禁用 iconv
                    -DDISABLE_ICONV=ON \
                    -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX \
                    ..
            nmake

        # 工作流运行结束后，在Git仓库的 Actions → 对应运行记录 → Artifacts 中会生成一个压缩包（如 windows-build.zip），供手动下载。
        - name: Upload Build Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: windows-build
            path: |
              /freetds/**/*
              ./build/**/*

        # 当推送 vX.Y.Z 标签时，自动将构建文件附加到GitHub Release中。
        - name: Create Release
          if: startsWith(github.ref, 'refs/tags/')
          uses: actions/create-release@v1
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            artifacts: ./build/**/*  # 或指定/freetds下的文件
